// @flow

const en = new Map([
    ['he', new Map([
        ['nominativeSubject', 'he'],
        ['obliqueObject', 'him'],
        ['possessiveDeterminer', 'his'],
        ['possessivePronoun', 'his'],
        ['reflexive', 'himself'],
        ['generic', 'man'],
        ['honorific', 'mr'],
        ['junior', 'boy'],
    ])],
    ['she', new Map([
        ['nominativeSubject', 'she'],
        ['obliqueObject', 'her'],
        ['possessiveDeterminer', 'her'],
        ['possessivePronoun', 'hers'],
        ['reflexive', 'herself'],
        ['generic', 'woman'],
        ['honorific', ['ms', 'mrs', 'miss']],
        ['junior', 'girl'],
    ])],
    ['they', new Map([
        ['nominativeSubject', 'they'],
        ['obliqueObject', 'them'],
        ['possessiveDeterminer', 'their'],
        ['possessivePronoun', 'theirs'],
        ['reflexive', 'themself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['e', new Map([
        ['nominativeSubject', 'e'],
        ['obliqueObject', 'em'],
        ['possessiveDeterminer', 'eir'],
        ['possessivePronoun', 'eirs'],
        ['reflexive', 'eirself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['ey', new Map([
        ['nominativeSubject', 'ey'],
        ['obliqueObject', 'em'],
        ['possessiveDeterminer', 'eir'],
        ['possessivePronoun', 'eirs'],
        ['reflexive', 'emself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['tho', new Map([
        ['nominativeSubject', 'tho'],
        ['obliqueObject', 'thor'],
        ['possessiveDeterminer', 'thors'],
        ['possessivePronoun', 'thor'],
        ['reflexive', 'thongself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['hu', new Map([
        ['nominativeSubject', 'hu'],
        ['obliqueObject', 'hum'],
        ['possessiveDeterminer', 'hus'],
        ['possessivePronoun', 'hus'],
        ['reflexive', 'humself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['per', new Map([
        ['nominativeSubject', 'per'],
        ['obliqueObject', 'per'],
        ['possessiveDeterminer', 'per'],
        ['possessivePronoun', 'pers'],
        ['reflexive', 'perself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['thon', new Map([
        ['nominativeSubject', 'thon'],
        ['obliqueObject', 'thon'],
        ['possessiveDeterminer', 'thons'],
        ['possessivePronoun', 'thons'],
        ['reflexive', 'thonself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['jee', new Map([
        ['nominativeSubject', 'jee'],
        ['obliqueObject', 'jem'],
        ['possessiveDeterminer', 'jeir'],
        ['possessivePronoun', 'jeirs'],
        ['reflexive', 'jemself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['ve', new Map([
        ['nominativeSubject', 've'],
        ['obliqueObject', 'ver'],
        ['possessiveDeterminer', 'vis'],
        ['possessivePronoun', 'vis'],
        ['reflexive', 'verself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['xe', new Map([
        ['nominativeSubject', 'xe'],
        ['obliqueObject', 'xem'],
        ['possessiveDeterminer', 'xyr'],
        ['possessivePronoun', 'xyrs'],
        ['reflexive', 'xemself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['ze', new Map([
        ['nominativeSubject', 'ze'],
        ['obliqueObject', 'mer'],
        ['possessiveDeterminer', 'zer'],
        ['possessivePronoun', 'zers'],
        ['reflexive', 'zemself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])],
    ['zhe', new Map([
        ['nominativeSubject', 'zhe'],
        ['obliqueObject', 'zhim'],
        ['possessiveDeterminer', 'zher'],
        ['possessivePronoun', 'zhers'],
        ['reflexive', 'zhimself'],
        ['generic', 'person'],
        ['honorific', 'mx'],
        ['junior', 'child'],
    ])]
]);
export default en;